export default [
    {
        id: 1,
        sideStatus: true,
        emojiSide: "🐄",
        wordSide: "Cow",
    },
    {
        id: 2,
        sideStatus: true,
        emojiSide: "🍎",
        wordSide: "Apple",
    },
    {
        id: 3,
        sideStatus: true,
        emojiSide: "👽",
        wordSide: "Alien",
    },
    {
        id: 4,
        sideStatus: true,
        emojiSide: "☂️",
        wordSide: "Umbrella",
    },
    {
        id: 5,
        sideStatus: true,
        emojiSide: "🦎",
        wordSide: "Lizard",
    },
    {
        id: 6,
        sideStatus: true,
        emojiSide: "🦔",
        wordSide: "Hedgehog",
    },
    {
        id: 7,
        sideStatus: true,
        emojiSide: "🌈",
        wordSide: "Rainbow",
    },
    {
        id: 8,
        sideStatus: true,
        emojiSide: "🌼",
        wordSide: "Flower",
    },
    {
        id: 9,
        sideStatus: true,
        emojiSide: "🍕",
        wordSide: "Pizza",
    },
    {
        id: 10,
        sideStatus: true,
        emojiSide: "🐠",
        wordSide: "Fish",
    },
    {
        id: 11,
        sideStatus: true,
        emojiSide: "🍭",
        wordSide: "Candy",
    },
    {
        id: 12,
        sideStatus: true,
        emojiSide: "🚀",
        wordSide: "Rocket",
    },
    {
        id: 13,
        sideStatus: true,
        emojiSide: "🌞",
        wordSide: "Sun",
    },
    {
        id: 14,
        sideStatus: true,
        emojiSide: "🌈",
        wordSide: "Rainbow",
    },
    {
        id: 15,
        sideStatus: true,
        emojiSide: "🐻",
        wordSide: "Bear",
    },
    {
        id: 16,
        sideStatus: true,
        emojiSide: "🌸",
        wordSide: "Flower",
    },
    {
        id: 17,
        sideStatus: true,
        emojiSide: "🍦",
        wordSide: "Ice Cream",
    },
    {
        id: 18,
        sideStatus: true,
        emojiSide: "🐶",
        wordSide: "Dog",
    },
    {
        id: 19,
        sideStatus: true,
        emojiSide: "🎈",
        wordSide: "Balloon",
    },
    {
        id: 20,
        sideStatus: true,
        emojiSide: "🌼",
        wordSide: "Flower",
    },
];
